### ISSUE TITLE
error: type arguments cannot be applied to non-parameterized class 'NSMutableArray'

### ISSUE THREAD

**Issue by tels7ar** [MaddTheSane/NetHack-Mac-OS-X#1]
I'm trying to build on macos 10.10.5 and getting this error:

```
gcc -fobjc-arc -I../win/cocoa/iHack -I../win/cocoa -I. -Wall -Wextra -Wno-missing-field-initializers -Wimplicit -Wreturn-type -Wunused -Wformat -Wswitch -Wshadow -Wwrite-strings -DGCC_WARN -std=gnu99 -g -I../include -DNOMAIL -DNOTPARMDECL -DHACKDIR=\"/Users/phollenback/nethackdir\" -DDEFAULT_WINDOW_SYS=\"cocoa\" -UDLB -DGREPPATH=\"/usr/bin/grep\" -DCOCOA_GRAPHICS -mmacosx-version-min=10.9 -DNOTTYGRAPHICS -DSYSCF -DSYSCF_FILE=\"/Users/phollenback/nethackdir/sysconf\" -DSECURE ../win/cocoa/DirectionWindowController.m -c -o DirectionWindowController.o
In file included from ../win/cocoa/DirectionWindowController.m:26:
../win/cocoa/iHack/NhEventQueue.h:33:2: error: type arguments cannot be applied to non-parameterized class 'NSMutableArray'
```

My gcc reports:

```
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

Steps to build:
1. cd ~/git/NetHack-Mac-OS-X/win/cocoa
2. bash ./bootstrap.sh
3. cd ~/git/NetHack-Mac-OS-X/
4. make

**Comment by MaddTheSane** [comment]
The code does have some enhancements that make it play better with Swift code. However, they use features introduced with the tools of Xcode 7.2.

There's also an Xcode project in `win/cocoa/`, which is mainly what I use to build. If that doesn't work, I can always build the project for you.

**Comment by tels7ar** [comment]
Ah, I'm on xcode 7.1.  Upgrading now.

**Comment by tels7ar** [comment]
Tried xcode 7.2, same failure.  Can't try 7.3 because I'm still on Yosemite and 7.3 requires El Capitan.  Will try the Xcode project.

**Comment by tels7ar** [comment]
Xcode project worked!
